version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cavabien
      MYSQL_DATABASE: cavabien
      MYSQL_USER: cavabien
      MYSQL_PASSWORD: cavabien
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  webserver:
    image: nginx
    working_dir: /application
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./public:/var/www/html/public
      - ./storage/logs/nginx/:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

volumes:
  db:
